import Vue from 'vue';

import MDIAccount from 'vue-material-design-icons/Account.vue';
import MDIAccountCash from 'vue-material-design-icons/AccountCash.vue';
import MDIAccountMultiple from 'vue-material-design-icons/AccountMultiple.vue';
import MDIArchive from 'vue-material-design-icons/Archive.vue';
import MDIBell from 'vue-material-design-icons/Bell.vue';
import MDIBullhorn from 'vue-material-design-icons/Bullhorn.vue';
import MDICalendar from 'vue-material-design-icons/Calendar.vue';
import MDIChevronRight from 'vue-material-design-icons/ChevronRight.vue';
import MDICreditCard from 'vue-material-design-icons/CreditCard.vue';
import MDIEmail from 'vue-material-design-icons/Email.vue';
import MDIFileDocument from 'vue-material-design-icons/FileDocument.vue';
import MDIFileDocumentMultiple from 'vue-material-design-icons/FileDocumentMultiple.vue';
import MDIFileUpload from 'vue-material-design-icons/FileUpload.vue';
import MDIHome from 'vue-material-design-icons/Home.vue';
import MDILoading from 'vue-material-design-icons/Loading.vue';
import MDIMenu from 'vue-material-design-icons/Menu.vue';
import MDIPencil from 'vue-material-design-icons/Pencil.vue';
import MDIPower from 'vue-material-design-icons/Power.vue';

Vue.component('mdi-account', MDIAccount);
Vue.component('mdi-account-cash', MDIAccountCash);
Vue.component('mdi-account-multiple', MDIAccountMultiple);
Vue.component('mdi-archive', MDIArchive);
Vue.component('mdi-bell', MDIBell);
Vue.component('mdi-bullhorn', MDIBullhorn);
Vue.component('mdi-calendar', MDICalendar);
Vue.component('mdi-chevron-right', MDIChevronRight);
Vue.component('mdi-credit-card', MDICreditCard);
Vue.component('mdi-email', MDIEmail);
Vue.component('mdi-file-document', MDIFileDocument);
Vue.component('mdi-file-document-multiple', MDIFileDocumentMultiple);
Vue.component('mdi-file-upload', MDIFileUpload);
Vue.component('mdi-loading', MDILoading);
Vue.component('mdi-home', MDIHome);
Vue.component('mdi-menu', MDIMenu);
Vue.component('mdi-pencil', MDIPencil);
Vue.component('mdi-power', MDIPower);
